 steps:
 # use composer image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/kms', '.']
   dir: 'kms/'
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/kms']
   dir: 'kms/'
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
   - 'run'
   - 'deploy'
   - 'kmsservice'
   - '--image'
   - 'gcr.io/$PROJECT_ID/kms'
   - '--region'
   - 'us-east1'
   - '--platform'
   - 'managed'
   - '--allow-unauthenticated'
 images: ['gcr.io/$PROJECT_ID/kms']
